spring:
  main:
    web-application-type: reactive

  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: example-service
          uri: http://localhost:8081
          predicates:
            - Path=/example/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/houses96

server:
  port: 8080
